---
- hosts: webservers
  become: yes
  tasks: 
  - name: intall git 1
    yum: 
      namee: git
      state: present
    ignore_errors: yes
    
  - name: install tree 2
    yum:
      name: tree
      state: present

  - name: install wget 3
    yum:
      name: wget
      state: present
    
