---
- hosts: webservers
  become: yes
  tasks:
  - name: install java on ubuntu
    apt:
      name: "{{javaonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"
  - name: install java on redhattt
    yum:
      name: "{{javaonredhat}}"
      state: present
    when: ansible_os_family =="RedHat"

